### ISSUE TITLE
Init infrastructure for scalable and extensive features and functions

### ISSUE THREAD

**Issue by haodev007** [extensive-weird/extensive-next-app#1]

**Comment by haodev007** [comment]
Hi @RedBlood639 
Please figure out this issues.
You should be able to init Next.js project structure so we can add lots of functions and maintain easily this project.
Please start it right now.

**Comment by RedBlood639** [comment]
Yeah, I will change and Update soon

**Comment by haodev007** [comment]
> Yeah, I will change and Update soon

Please work on staging branch and create PR with your updates.

**Comment by RedBlood639** [comment]
I just made new PR to main branch, please check.

**Comment by haodev007** [comment]
Ok, I will review it, thanks for your quick work
